### PR TITLE
Add html and css files

### PR DESCRIPTION
**Pull request by simplegoose**
Add index.html file and style.css file
- Create an index.html file and edit its content by adding HTML.
- Create a style.css file and add CSS rules inside the file.
- Link style.css inside index.html.

### CODE REVIEW

**Review by mukhammadrizooff — CHANGES_REQUESTED** [review]
Hi @simplegoose, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- Descriptive commit history ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
- [x] [REQUIRED] Good job so far! Please add more information about this milestone to your `Pull Request` Description because `Pull Request` should have a descriptive `title` telling you what changes are inside and `summary` describing introduced changes in `more detail`🙏 

image

- [ ] [REQUIRED] Please implement my suggestions! Please fix your `Github Linter Actions`, please check again them [based on the list](https://github.com/microverseinc/linters-config/tree/master/html-css) provided by `Microverse` because your 'Github Linter Actions' are not running 🙏 

image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by simplegoose** [comment]
Hello @mukhammadrizooff

Thank you for the review. If I want to remove the linting errors, on which branch should I push the changes? Thanks.

**Comment by mukhammadrizooff** [comment]
> Hello @mukhammadrizooff
> 
> Thank you for the review. If I want to remove the linting errors, on which branch should I push the changes? Thanks.

Current branch 👍

**Comment by simplegoose** [comment]
Hello @mukhammadrizooff 
I pushed the changes to the current branch but the changes took no effect.

**Review by huseyinbiyik — APPROVED** [review]
Hi @simplegoose 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Linters are passing 🟢
- Requested changes implemented well 👌

## Optional suggestions
- [OPTIONAL] Please delete the logo on the top of the Readme file if you have your own logo you can use it instead of the default one.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
